ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyUSB_EMU

STORM_LIB_PATH = /home/dmb/catkin_ws/src/storm/sketchbook/libraries
USER_LIB_PATH = $(STORM_LIB_PATH)
ARDUINO_LIBS = ros_lib PinChangeInt Servo
BOARD_TAG = uno

include /usr/share/arduino/Arduino.mk
